### ISSUE TITLE
Daha fazla detay linki yanlış yere yönlendiriyor

### ISSUE THREAD

**Issue by mustaphaturhan** [eserozvataf/eserozvataf#2]
`README` metninde geçen "Daha fazla detay için [eser.ozvataf.com](eser.ozvataf.com) adresine uğrayabilirsiniz." kısmı `eser.ozvataf.com` adresine yönlendirmesi gerekiyorken `https://github.com/eser.ozvataf.com` adresine yönlendiriyor.

### Hatayı nasıl yeniden üretebilirim?
- https://github.com/eserozvataf adresine git.
-  eser.ozvataf.com adresine tıkla.

### Çözüm önerileri
`"Daha fazla detay için [eser.ozvataf.com](https://eser.ozvataf.com) adresine uğrayabilirsiniz."` şeklinde değiştirmek.

**Comment by eser** [comment]
bunu çok sonra gördüm, çok teşekkürler :)

**Comment by mustaphaturhan** [comment]
@eserozvataf issue'nun fixlendiğini görünce close etmiştim :)
